spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${gateway.services.auth.uri}/.well-known/jwks.json
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-public
              uri: 'lb://${gateway.services.auth.service-name}'
              predicates:
                - Path=/public/auth/**
              filters:
                - StripPrefix=2
                - PrefixPath=/api/public
            - id: game-clicker-service-public
              uri: 'lb://${gateway.services.game-clicker.service-name}'
              predicates:
                - Path=/public/game-clicker/**
              filters:
                - StripPrefix=2
                - PrefixPath=/api/public
            - id: game-clicker-service-admin
              uri: 'lb://${gateway.services.game-clicker.service-name}'
              predicates:
                - Path=/admin/game-clicker/**
              filters:
                - StripPrefix=2
                - PrefixPath=/api/admin

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 9000

gateway:
  services:
    auth:
      uri: ${AUTH_SERVICE_HOST_URL:http://localhost:5000}
      service-name: auth-service
    game-clicker:
      uri: ${GAME_CLICKER_SERVICE_HOST_URL:http://localhost:5001}
      service-name: game-clicker-service
    frontend:
      uri: http://localhost:3000

management:
  endpoints:
    web:
      exposure:
        include: "health,info,loggers,beans,metrics"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.server: TRACE
    org.springframework.security.authorization: TRACE
    org.springframework.security.web.server.authorization: TRACE
    org.springframework.security.web.server.authorization.AuthorizationWebFilter: TRACE
    org.springframework.security.web.server.authorization.AuthorizationContext: TRACE
    org.springframework.security.web.server.util.matcher: TRACE