spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yaroslav.shestukhin@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 761706611693-vu8eit6acq8ooa6c897i7ff3h25kcdnj.apps.googleusercontent.com
            redirect-uri: "http://localhost:9000/auth/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: auth_service
    driver-class-name: org.postgresql.Driver
  jpa:
    enabled: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.authorization: DEBUG
    org.hibernate.cfg: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.boot.model.naming: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,loggers,beans"
  endpoint:
    health:
      show-details: ALWAYS